version: "3.8"
services:

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      # postgres env vars
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      # 5432 standard for pg dbs
      - ${PG_PORT}:${PG_CONTAINER_PORT}
    volumes:
      # not seeding data, only applying schema
      # and mapping a dir where we can add
      # the .csv files we'll use to populate the db
      - ./data:/var/lib/postgresql/data
      - ./products.sql:/docker-entrypoint-initdb.d/products.sql

